file <-read.table("household_power_consumption.txt", header = T, sep = ";", na.strings = "?", stringsAsFactors = F)
file <- na.omit(file)
library(dplyr)
file <- tbl_df(file)
feb <- filter(file, Date == "1/2/2007" | Date == "2/2/2007")
feb$DT <- paste(feb$Date, feb$Time)
feb$DT <- strptime(feb$DT, "%d/%m/%Y%H:%M:%S")
with(feb, plot(DT, Global_active_power, type = "l", ylab = "Global Active Power(kilowatts)"))
dev.copy(png, file = "Plot 2")
dev.off()